const variable = ["입장료 없음", "7,000원 ~ 9,000원", "전용 주차장"];
// placeId-561W
// address랑 카카오지도랑 연동 가능한지

export const database = [
  {
    id: "placeId561W",
    place_name: "속삭이는 자작나무 숲",
    region: "강원도 인제",
    image: [
      // "https://i.postimg.cc/8CnTnHWZ/image.png",
      // "https://i.postimg.cc/cC0k7qH2/image.png",
      "https://res.cloudinary.com/dnmb6kxvh/image/upload/v1721923577/acuk38elplh0jg2cbv8c.png",
      "https://res.cloudinary.com/dnmb6kxvh/image/upload/v1721923637/e9dbat9sydxririky8lv.png",
    ],
    description:
      "강원도 인제군 원대리 숲속에서 매양 당신을 기다리는 나무가 있다. 피부는 백옥 같고 키는 훤칠하다. 이 멋진 자작나무의 꽃말은 '당신을 기다립니다'이다.",
    address: "강원도 인제군 인제읍 자작나무싶길 760",
    map: null,
    blog_search_url: null,
    reviews: [],
    theme: "healing",
    options: ["입장료 없음", "전용 주차장"],
    phone: "033-463-0044",
    homepage: "",
    hashtags: ["#힐링", "#풍경", "#강원도"],
  },
  {
    id: "placeId992f",
    place_name: "아침고요 수목원",
    region: "경기도 가평",
    image: [
      "https://i.postimg.cc/gkw8MSZT/image.png",
      "https://i.postimg.cc/KzPxvywH/image.png",
    ],
    description:
      "가평의 축령산 기슭에 숨바꼭질 하듯 숨어있다. 잣나무 숲이 빽빽하여 가는 길도 아름답고, 산 아래 비밀 화원은 동화 속을 걷는 듯 즐겁고 꿈결인 듯 신비롭다.",
    address: "경기도 가평군 상면 수목원로 432",
    map: null,
    blog_search_url: null,
    reviews: [],
    theme: "healing",
    options: ["6,000원 ~ 10,000원", "전용 주차장"],
    phone: "1544-6703",
    homepage: "https://www.morningcalm.co.kr/html/preview02.php",
    hashtags: ["#힐링", "#풍경", "#강원도"],
  },
  {
    id: "placeId487f",
    place_name: "대관령 양떼 목장",
    region: "강원도 평창",
    image: [
      "https://res.cloudinary.com/dnmb6kxvh/image/upload/v1722185855/igti7mox0mwyg476cgud.png",
      "https://res.cloudinary.com/dnmb6kxvh/image/upload/v1722185871/ddpyfe7a0dkag22u0xge.png",
    ],
    description:
      "여기 우리나라 맞아? 대관령 양떼목장에 들어서면, 순간 이동을 해 스위스으 ㅣ목장 마을에 온 기분이 든다. 목가적인 서정과 이국적인 감성을 더불어 느낄 수 있다.",
    address: "강원도 평창군 대관령면 대관령마루길 483-32",
    map: null,
    blog_search_url: null,
    reviews: [],
    theme: "scenic",
    options: ["7,000원 ~ 9,000원", "전용 주차장"],
    phone: "033-335-1966",
    homepage: "https://yangtte.co.kr/",
    hashtags: ["#힐링", "#풍경", "#강원도"],
  },
  {
    id: "placeId123f",
    place_name: "안반데기",
    region: "강원도 강릉",
    image: [
      "https://res.cloudinary.com/dnmb6kxvh/image/upload/v1722185780/wydqutpfjsikdk6ikwxq.png",
      "https://res.cloudinary.com/dnmb6kxvh/image/upload/v1722185793/m6kztpy63lqco1p9fpdu.png",
    ],
    description:
      "경이롭다. 입이 떡 벌어지고 감탄사가 절로 나온다. 해발 1,100m! 북한산 정상보다 더 높은 곳에 광활한 채소밭이 펼쳐져 있다. 채소밭 크기가 무려 60만 평이다.",
    address: "강원도 강릉시 왕산면 안반데기길 428",
    map: null,
    blog_search_url: null,
    reviews: [],
    theme: "healing",
    options: ["입장료 없음", "전용 주차장"],
    phone: "033-655-5119",
    homepage: "http://www.xn--ok0bo3h6vi1zj.kr/default/",
    hashtags: ["#힐링", "#풍경", "#강원도"],
  },
  {
    id: "placeId_dnjfwjdtk",
    place_name: "월정사",
    region: "강원도 평창",
    image: [
      "https://res.cloudinary.com/dnmb6kxvh/image/upload/v1722185736/rlbhzqxmdgcquvbtoaua.png",
      "https://res.cloudinary.com/dnmb6kxvh/image/upload/v1722185752/txgjoqhnvestgv5hgyb5.png",
    ],
    description:
      "전나무숲길이 아름다운 절이다. 일주문부터 금강교까지 아름드리 전나무가 숲길을 만들고 있다. 숲길에 접어드는 순간, 사람들은 누구나 행복한 고요에 젖는다",
    address: "강원도 평창군 진부면 오산대로 374-8",
    map: null,
    blog_search_url: null,
    reviews: [],
    theme: "healing",
    options: ["500원~5000원", "월정사 주차장"],
    phone: "033-339-6800",
    homepage: "http://www.woljeongsa.org/intro.php",
    hashtags: ["#힐링", "#풍경", "#강원도"],
  },
  {
    id: "placeId_rlftkdtk",
    place_name: "길상사",
    region: "서울 성북구",
    image: [
      "https://res.cloudinary.com/dnmb6kxvh/image/upload/v1722185707/xeoxfrb3ipuvx41twixn.png",
      "https://res.cloudinary.com/dnmb6kxvh/image/upload/v1722185721/rlpsbqoc6ppxtgq5luz7.png",
    ],
    description:
      "일주문을 지나면 공기가 확 바뀐다. 도심 사찰인데 마치 산 속에 들어와 있는 것 같다. 법정 스님과 시인 백석, 그리고 백석이 사랑한 여인 김영한을 떠올려보자.",
    address: "서울시 성북구 선잠로5길 68",
    map: null,
    blog_search_url: null,
    reviews: [],
    theme: "healing",
    options: ["", ""],
    phone: "02-3672-5945",
    homepage: "http://kilsangsa.info/home/default_in.asp",
    hashtags: ["#힐링", "#풍경", "#강원도"],
  },
  {
    id: "placeId_뮤지엄산",
    place_name: "뮤지엄산",
    region: "강원도 원주",
    image: [
      "https://res.cloudinary.com/dnmb6kxvh/image/upload/v1722185676/uednnvtsx5kvewzbvd8t.png",
      "https://res.cloudinary.com/dnmb6kxvh/image/upload/v1722185691/fzlqwywpz799qtamxwmm.png",
    ],
    description:
      "최고 수준의 조형미를 보여주는 건축과 예술이, 원주의 골프장 옆 해발 275m 산 위에서 당신을 기다린다. 미술관을 둘러보고 나면 행복감이 부드럽게 몸을 감싼다",
    address: "강원도 원주시 지정면 오크벨리 2길 260",
    map: null,
    blog_search_url: null,
    reviews: [],
    theme: "art",
    options: ["14,000원 ~ 40,000원", "전용 주차장", "매주 월요일 휴관"],
    phone: "0507-1430-9001",
    homepage: "https://www.museumsan.org/museumsan/#none",
    hashtags: ["#힐링", "#풍경", "#강원도"],
  },
  {
    id: "placeId_하슬라아트월드",
    place_name: "하슬라아트월드",
    region: "강원도 강릉",
    image: [
      "https://res.cloudinary.com/dnmb6kxvh/image/upload/v1722185626/lxoalyjvfzmxwsqllcza.png",
      "https://res.cloudinary.com/dnmb6kxvh/image/upload/v1722185641/xwpp1vz1ipc2rnse2vcg.png",
    ],
    description:
      "강릉 정동진쪽 산 위에 있다. 하슬라 아트월드로 들어서면 새로운 세계가 열리는 것 같다. 푸른 바다를 배경으로 조각공원, 미술관, 박물관이 차례로 반겨준다",
    address: "강원도 강릉시 강동면 율곡로 1441",
    map: null,
    blog_search_url: null,
    reviews: [],
    theme: "art",
    options: ["11,000원 ~ 15,000원", "전용 주차장"],
    phone: "033-644-9411",
    homepage: "https://www.museumhaslla.com/",
    hashtags: ["#힐링", "#풍경", "#강원도"],
  },
];

const basic = {
  id: "",
  place_name: "",
  region: "",
  image: ["", ""],
  description: "",
  address: "",
  map: null,
  blog_search_url: null,
  reviews: [],
  theme: "",
  options: ["", ""],
  phone: "",
  homepage: "",
  hashtags: ["", ""],
};
